spring: 
 profiles: 
  active: 
  - dev
---
server:
  port: 8001
  
mybatis:
  type-aliases-package: com.whstone.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

spring:
 profiles: dev
 application:
  name: microservice-dept
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.gjt.mm.mysql.Driver
  url: jdbc:mysql://192.168.56.101:3306/cloudDB01
  username: root
  password: 123456
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-millis: 200
---
server:
  port: 8011
  
mybatis:
  type-aliases-package: com.whstone.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

spring:
 profiles: test
 application:
  name: microservice-dept
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.gjt.mm.mysql.Driver
  url: jdbc:mysql://192.168.56.101:3306/cloudDB01
  username: root
  password: 123456
  dbcp2:
    min-idle: 5
    initial-size: 5
    max-total: 5
    max-wait-millis: 200